rootProject.name = "kotlinx-gtk"
include("nativex")
include("nativex:gio")
include("nativex:glib-object")
include("nativex:glib")
include("nativex:cairo")
include("nativex:pango")
include("dsl")
include("example")
include("demos:widget-factory")
include("demos:packing")
include("demos:combobox")
include("demos:gtk-demo")