package org.gtk.gtk.common.enums

import gtk.*

/**
 * kotlinx-gtk
 * 06 / 03 / 2021
 */
enum class StateFlags(val gtk: GtkStateFlags) {
	NORMAL(GTK_STATE_FLAG_NORMAL),
	ACTIVE(GTK_STATE_FLAG_ACTIVE),
	PRELIGHT(GTK_STATE_FLAG_PRELIGHT),
	SELECTED(GTK_STATE_FLAG_SELECTED),
	INSENSITIVE(GTK_STATE_FLAG_INSENSITIVE),
	INCONSISTENT(GTK_STATE_FLAG_INCONSISTENT),
	FOCUSED(GTK_STATE_FLAG_FOCUSED),
	BACKDROP(GTK_STATE_FLAG_BACKDROP),
	DIR_LTR(GTK_STATE_FLAG_DIR_LTR),
	DIR_RTL(GTK_STATE_FLAG_DIR_RTL),
	LINK(GTK_STATE_FLAG_LINK),
	VISITED(GTK_STATE_FLAG_VISITED),
	CHECKED(GTK_STATE_FLAG_CHECKED),
	DROP_ACTIVE(GTK_STATE_FLAG_DROP_ACTIVE);

	companion object {
		fun valueOf(gtk: GtkStateFlags) =
			values().find { it.gtk == gtk }
	}
}